apiVersion: v1 
kind: pod
metadata: 
   name: frontend  
   labels: 
       project: roboshop 
       component: frontend 
       environment: dev 
       Version: v1 
spec: 
   containers: 
   - name: frontend
     image: nginx 
           